### ISSUE TITLE
Error enumerating devices on Ubuntu 18.04

### ISSUE THREAD

**Issue by fpagliughi** [Smithay/udev-rs#11]
Running the *list_devices* example on Ubuntu 18.04 produces an error:
```
$ ./target/debug/examples/list_devices
Error: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
```
This is with the current code in the master branch. Trying it from v0.3 gives a different error:
```
$ ./target/debug/examples/list_devices
Error: Custom { kind: Other, error: "Unknown error -12" }
```
The error is the same, in either case, when run with root priveleges. The code that was in v0.2 worked on this computer.

**Comment by a1ien** [comment]
It seems that for older versions of libudev context is needed.
https://github.com/systemd/systemd/blob/v229/src/libudev/libudev-enumerate.c#L74

But in this 2e00c49f618c05d7cef076ddb14ad9de3897c261 commit we remove `Context`
