### ISSUE TITLE
set_attribute_value() error

### ISSUE THREAD

**Issue by wcampbell0x2a** [Smithay/udev-rs#15]
example code: 
```
// <- example code from monitor example
check_device(device);

fn check_device(mut device: udev::Device) -> std::io::Result<()> {
    device.set_attribute_value("authorized", "0")
}
```

error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: -6, kind: Other, message: "Unknown error -6" }', src/main.rs:92:17
```

If I ignore the error and then print using `device.attribute_value("authorized")` after calling `check_device()`
```
idProduct = Some("5567")
idVendor = Some("0781")
serial = Some("4C530011100520105420")
authorized = Some("")
product = Some("Cruzer Blade")
```

**Comment by Drakulix** [comment]
This seems to be a permission error or similar.
Code 6 is ENXIO on most Unix Systems, which might occur, when accessing sysfs device attributes (as noted e.g. here: https://www.kernel.org/doc/html/latest/admin-guide/sysfs-rules.html).

So not an error of udev-rs, but either of libudev or usage.
