### ISSUE TITLE
Socket should have iter method instead of consuming self

### ISSUE THREAD

**Issue by TomzBench** [Smithay/udev-rs#35]
It is strange to clone the socket when looping. I think it is more normal to see something like

```
for ev = socket.iter() {
} 
```

This would mean creating something like `SocketEventIter` and Socket would implement an `iter()` routine that returns SocketEventIter. Then, SocketEventIter would implement Iterator trait.  You could then do the clone of the ffi object internally in the iter method and hide the  user from calling clone.

Otherwise it kind of looks suspicious... The way it works now is that rust is implicitly converting the Socket into an iterator since it implements iterator on itself, and IntoITer has a `self` receiver and is forcing you to clone. But the implicit conversion should be better understood with a more explicit `iter` method, which would avoid the clone by the caller.

Also, it might not be a good idea to allow the socket to be cloned in the first place. because it implies that possibly it is a single producer multi receiver type.  But that is not likely the case, as only one receiver will see an event. Where a user who cloned the socket might expect both clones to receive the event. 

So if two sockets (1 + a clone) are able to receive the same event, then cloning is ok, otherwize it might be best to remove the derive Clone. I'm not sure how the binding works when you receive events, but the clone implies multi consumer type.

**Comment by Drakulix** [comment]
Sure, feel free to make a PR.

**Comment by TomzBench** [comment]
@Drakulix ok i added pr here: https://github.com/Smithay/udev-rs/pull/36

It is breaking the api for iterating on event messages so i am not sure best way to go from here

**Comment by Drakulix** [comment]
> It is breaking the api for iterating on event messages so i am not sure best way to go from here

I can handle that, once the PR is green and everything tested, I'll make sure to release a 0.7 version in time.

**Comment by TomzBench** [comment]
When using Poll, why does the monitor have to be registered with Interest::WRITABLE?  I would think that a udev event would signal a READABLE event.  But poll won't work unless registered as both READABLE and WRITABLE.

**Comment by Drakulix** [comment]
> When using Poll, why does the monitor have to be registered with Interest::WRITABLE? I would think that a udev event would signal a READABLE event. But poll won't work unless registered as both READABLE and WRITABLE.

I cannot tell you, I have also found this odd.

**Comment by Drakulix** [comment]
Closing this issue now, 0.7.0 is released. Thanks for the contribution!

**Comment by TomzBench** [comment]
> I cannot tell you, I have also found this odd.

alright - as long as i|m not the only one.

...Thanks for merging and maintaining udev-rs
