### ISSUE TITLE
udev::Device::from_devnum(...) breaks compilation on many targets.

### ISSUE THREAD

**Issue by tim-seoss** [Smithay/udev-rs#42]
Firstly thanks for writing and maintaining udev-rs!

I found that the new (but as-yet unreleased) `udev::Device::from_devnum()` associated functions break compilation on ARM Linux.  The current code only works on platforms where `c_char` is defined as `i8`.  On platforms which instead define `c_char` as `u8`, compilation fails (it's defined as `u8` on approx half the platforms which the rust libc crate supports).

See: https://doc.rust-lang.org/std/os/raw/type.c_char.html

The signatures are currently of the form:

```rust
pub fn from_devnum(dev_type: u8, devnum: dev_t) -> Result<Self> {...}
```

The simplest fix is to just change the `as i8` to `as c_char`:

```diff
pub fn from_devnum_with_context(udev: Udev, dev_type: u8, devnum: dev_t) -> Result<Self> {
-            ffi::udev_device_new_from_devnum(udev.as_raw(), dev_type as i8, devnum)
+            ffi::udev_device_new_from_devnum(udev.as_raw(), dev_type as c_char, devnum)
});
```

... alternatively to provide a more rust-y interface, then something like this might be better:

```rust
use num_enum::TryFromPrimitive;

#[derive(TryFromPrimitive)]
#[repr(u8)]
pub enum DevType {
    Character = b'c',
    Block = b'b',
}

// ..

pub fn from_devnum(dev_type: self::DevType, devnum: dev_t) -> Result<Self> {
```

The user could then call as:

```rust
from_devnum(DevType::Character, dnum) {
```
... but still support semantics similar to the current version with:

```rust
from_devnum((b'c').try_into().unwrap(), dnum) {
```

Overall, I think the enum version would be more ergonomic, because (as far as I can see) in the typical use, there aren't any APIs which the caller can use that will return them a `b'c'` or `b'b'`.

e.g. The typical use would be to create a udev device based on information from the filesystem.  In order to do this, matching needs to be done on `st_rdev`.

Example code to do this (with the current unreleased API):

```rust
use std::{env, fs, os::linux::fs::MetadataExt};

fn main() -> std::io::Result<()> {
    let args: Vec<String> = env::args().collect();
    let path = args.get(1).expect("No filename given");
    let metadata = fs::metadata(path).unwrap_or_else(|_| panic!("Can't open file: {}", path));
    let devtype = match metadata.st_mode() & libc::S_IFMT {
        libc::S_IFCHR => b'c',
        libc::S_IFBLK => b'b',
        _ => 0,
    };
    if devtype == 0 {
        panic!("{} doesn't seem to be a character or block special file",
            path);
    }
    let ud = udev::Device::from_devnum(devtype, metadata.st_rdev())
        .expect("Couldn't construct udev from supplied path");
    println!("syspath of {} is {:?}", path, ud.syspath());
    Ok(())
}
```
The alternative enum version would look like:

```rust
use std::{env, fs, os::linux::fs::MetadataExt};
use udev::DevType;

fn main() -> std::io::Result<()> {
    let args: Vec<String> = env::args().collect();
    let path = args.get(1).expect("No filename given");
    let metadata = fs::metadata(path).unwrap_or_else(|_| panic!("Can't open file: {}", path));
    let devtype = match metadata.st_mode() & libc::S_IFMT {
        libc::S_IFCHR => Some(DevType::Character),
        libc::S_IFBLK => Some(DevType::Block),
        _ => None,
    }
    .unwrap_or_else(|| panic!("{} doesn't seem to be a character or block special file",
            path));
    let ud = udev::Device::from_devnum(devtype, metadata.st_rdev())
        .expect("Couldn't construct udev from supplied path");
    println!("udev syspath of {} is {:?}", path, ud.syspath());
    Ok(())
}
```

Whilst the enum version seems a bit more ergonomic, which version is best probably depends on the overall philosophy of the crate (and I'm not sure which fits best).

I'm happy to open a PR with either variant...

Cheers,

Tim.

**Comment by Drakulix** [comment]
Thanks for opening this issue. Feel free to write up a PR with the DevType enum! I would gladly review and merge it.

**Comment by tim-seoss** [comment]
I thought it better to name the enum DeviceType to avoid confusion with the devtype associated function (`dev_type` and `devtype` are completely different it seems 🤷‍♂️).  Since the underlying `from_devnum` is sparsely documented, and requires a lot of assumed knowledge (some of it somewhat arcane for correct usage), I've also extensively documented it.  If you have a minute to look at the draft PR #43, that would be great...
